### ISSUE TITLE
Research items for game page and turn into figma components

### ISSUE THREAD

**Issue by vuongb2** [info442-su23/h-team#11]
Create an item pool in Figma for the game page (include item, and incorrect/correct messages). This card should satisfy G2a of the requirements.md

**Comment by luckypanda88** [comment]
Here is the link to the Figma: 
[https://www.figma.com/file/pKrmEV5OAwsIy2wsPAPxKe/INFO-442-Design-Wireframes?type=design&node-id=201%3A175&mode=design&t=A91fgniAAzDgujdq-1](url)

**Comment by luckypanda88** [comment]
[https://www.figma.com/file/pKrmEV5OAwsIy2wsPAPxKe/INFO-442-Design-Wireframes?type=design&node-id=201%3A175&mode=design&t=NGb6FcbgRemA5cue-1](url)

**Comment by luckypanda88** [comment]
https://www.figma.com/file/pKrmEV5OAwsIy2wsPAPxKe/INFO-442-Design-Wireframes?type=design&node-id=201%3A175&mode=design&t=NGb6FcbgRemA5cue-1

**Comment by luckypanda88** [comment]
https://www.figma.com/file/pKrmEV5OAwsIy2wsPAPxKe/INFO-442-Design-Wireframes?type=design&node-id=201%3A175&mode=design&t=NGb6FcbgRemA5cue-1

**Comment by luckypanda88** [comment]
Here is the link to our Figma components: 
https://www.figma.com/file/pKrmEV5OAwsIy2wsPAPxKe/INFO-442-Design-Wireframes?type=design&node-id=201%3A175&mode=design&t=NGb6FcbgRemA5cue-1

**Comment by luckypanda88** [comment]
Here is the link to our Figma components: 
https://www.figma.com/file/pKrmEV5OAwsIy2wsPAPxKe/INFO-442-Design-Wireframes?type=design&node-id=201%3A175&mode=design&t=NGb6FcbgRemA5cue-1
