### ISSUE TITLE
Feature Request: The Page, "Special Cases", lacks the note that these specific cases can be applied to Washington Residents

### ISSUE THREAD

**Issue by ryo884-2177391** [info442-su23/h-team#36]
Overall, I really like your website, and the game activity is fun to play!! If I have one thing that I can report, I would say that there is no description that these special cases can be applied to the cases in Washington state (especially Seattle), so it will be helpful that you guys can add these notes to the paragraphs so that you will not confuse the users who concern of the global recycling.

**Comment by vuongb2** [comment]
We will add a disclaimer that these rules apply to the King County area! Thank you!

**Comment by luckypanda88** [comment]
Commit Link: https://github.com/info442-su23/h-team/commit/fd334b658630ef25acb2cc50802e872d2073fab3
