### ISSUE TITLE
Minor Bug (Hard to figure out the point of the handburger menu looking thing and the test is misaligned)

### ISSUE THREAD

**Issue by Mustafabd** [info442-su23/h-team#37]
- When I go to the game tab, the name of the item kind of overlaps with the photo of the item, and there are 3 lines under the name of the item that kind of give the impression of a handburger menu, so it prompts me to click it but nothing happens. 
- I am using microsoft edge
- Click on the game tab and look at the photo of the items to reproduce my steps
- I expected for there to not be overlap, and for the hamburger menu to be clickable
- in actuality, there was over lap between the name of the item and the photo of the item and the hamburger menu wasnt clickable
- 
<img width="282" alt="image" src="https://github.com/info442-su23/h-team/assets/80429899/fe595fdf-b691-4402-b880-7dbd33ac63d2">

**Comment by vuongb2** [comment]
We will expand the size of the card to contain all elements in the next sprint!

**Comment by atimch** [comment]
border branch:
https://github.com/info442-su23/h-team/activity?ref=border

**Comment by atimch** [comment]
To remove kebab AT#37: https://github.com/info442-su23/h-team/activity?ref=AT%2338
