### ISSUE TITLE
Minor Bug: Text and Image Overlap on Game Page

### ISSUE THREAD

**Issue by asingh0725** [info442-su23/h-team#38]
Summary: On the game page, the text "bread" and the image of the bread slightly overlap each other on a laptop-sized screen.
Environment: MacOS Chrome
Steps to reproduce: Open the webpage and click on the game link from the navbar menu
Actual Result: The text and image overlap
Expected Result: The text and image don't overlap

Image for reference: 
<img width="429" alt="Screenshot 2023-08-08 at 5 45 50 PM" src="https://github.com/info442-su23/h-team/assets/70999719/92b941d3-5a92-4a14-80ad-c48f5c2bba18">

**Comment by DongTianjia** [comment]
One more place when the text and the image overlap, makes is difficult to read: 
<img width="232" alt="Screen Shot 2023-08-09 at 13 10 35" src="https://github.com/info442-su23/h-team/assets/87292522/f663086f-0eb9-4956-9369-f33bc8774177">
Summary: On the game page, the text "Correct You dropped the item into the correct bin" and the image of the trash can overlap each other on a laptop-sized screen.
Environment: MacOS Chrome
Steps to reproduce: Open the webpage and click on the game link from the navbar menu, drag the item to the correct category.
Actual Result: The text and image overlap
Expected Result: The text and image don't overlap

**Comment by vuongb2** [comment]
This bug was already pointed out, but because it was within 3 minutes, I'm sure you didn't see!
