### ISSUE TITLE
Minor Bug: Footer not at the bottom on Game Page

### ISSUE THREAD

**Issue by asingh0725** [info442-su23/h-team#39]
Summary: On the game page, the footer is not at the bottom of the page.
Environment: MacOS Chrome
Steps to reproduce: Open the webpage and click on the game link from the navbar menu
Actual Result: The footer is not at the bottom of the page
Expected Result: The footer is at the bottom of the page.

Image for reference
<img width="533" alt="Screenshot 2023-08-08 at 5 48 00 PM" src="https://github.com/info442-su23/h-team/assets/70999719/48802a99-9256-4bdf-b9c3-9fd4bb0959fb">

**Comment by vuongb2** [comment]
Thanks Asingh, we will work on getting the footer to append to the bottom with css styling in our next spring!

**Comment by taylor-russon** [comment]
https://github.com/info442-su23/h-team/commit/1c09e1468b36cc98ebc60d00b50b94b1ba650480

1c09e14
