### ISSUE TITLE
Major bugs: Img from other media will also shows correct

### ISSUE THREAD

**Issue by VictoriaVVei** [info442-su23/h-team#41]
Summary: After I put img from other media, the game still shows I am correct.
Environment: Chrome on Win 11 (Version 115.0.5790.171)
Steps to reproduce: After I put one img from my local, the game will successful at the third try.
Expected result: Incorrect for other img.
Actual result: Correct for other img
Attachments:
![d7a50b7e7129c45d8890b5199730240](https://github.com/info442-su23/h-team/assets/91993339/a919156f-4fd0-4c26-8c84-513ed66a037d)

**Comment by vuongb2** [comment]
Hi Victoria, we don't consider this a Major bug but a sort of feature. Impressive find though!

**Comment by cherimarie** [comment]
This is a hilarious bug. It is a minor bug though, and should be labeled such. If you don't want to address it, it should also be labeled "wontfix".
