### ISSUE TITLE
 logo does not direct me to home page(minor)

### ISSUE THREAD

**Issue by jm278** [info442-su23/h-team#42]
On click of the logo on the navbar, it does not direct me to the homepage. 
Environment: macOS Catalina 
Steps to reproduce: checkout navbar
expected: navigate to the homepage when I click on the logo on the navbar 
actual result: nothing happened

**Comment by vuongb2** [comment]
Hi JM, thanks for your catch. Since we have a Home link, we don't plan on making the Happy Recycling link to anything (yet). Eventually, we may have it link to a different page, and make our homepage something else!
