### ISSUE TITLE
Feature Request ---- navigation bar

### ISSUE THREAD

**Issue by Zuoooooo** [info442-su23/h-team#46]
The font of the navigation bar can be larger, which helps users to see clearly.

The logo on the left side of the navigation bar can add functions. When users are on any page, they can click the logo and jump to the home page.

**Comment by Zuoooooo** [comment]
<img width="1440" alt="Screen Shot 2023-08-08 at 6 11 27 PM" src="https://github.com/info442-su23/h-team/assets/114701960/6d6a858f-6569-40bc-9ace-b3092a5bc7b5">

**Comment by vuongb2** [comment]
Duplicate: https://github.com/info442-su23/h-team/issues/42
