### ISSUE TITLE
feature request --- Learn Page

### ISSUE THREAD

**Issue by Zuoooooo** [info442-su23/h-team#47]
I think you can add some filter or search functions to the "Learn Page" to filter "What can I TRASH?", "What can I COMPOST?", etc., because when users want to find out whether something can be thrown away, they can only slide down the web pages to view them one by one, which is not conducive to the user's interaction with the web pages.

**Comment by taylor-russon** [comment]
This will be too much work to get done before this class is over, good idea tho!
