### ISSUE TITLE
Description for each item in recycle game (Feature request)

### ISSUE THREAD

**Issue by FastFusion5** [info442-su23/h-team#48]
Currently, dragging items into the bins for the recycle game only displays correct and incorrect. It would be nice to add a short description beside each item so that people understand why they go in that respective category as well as the potential hazards of incorrectly throwing items into the wrong category. This enhances the educational aspect of the game and allows people to understand the significance of waste sorting to the environment.

**Comment by vuongb2** [comment]
Duplicate: https://github.com/info442-su23/h-team/issues/43
