### ISSUE TITLE
Bug Minor: Contact Us issue

### ISSUE THREAD

**Issue by wphan-1925132** [info442-su23/h-team#49]
Used Chrome on Windows
Used Safari on IOS iPhone
The "contact us" link at the bottom of the page doesn't work well. When clicked on, instead of giving me options of how to contact or simply giving me the email or form, it forces my laptop to open up the "Mail" application on my device which is not linked to anything and is not setup so I'm not able to see the email address. Same with on the iPhone, when clicked on, instead of directing me to my gmail or mail app that is set up, it leads me to setup a new email on my phone and I never get to simply see the email address. I think a better solution would to simple create a popup to show the email or any form of contacting, maybe even a fill out form.

![image](https://github.com/info442-su23/h-team/assets/56050048/c8e5256a-80fe-41d5-bbc9-96d7eb6854e7)

**Comment by taylor-russon** [comment]
In our requirements we planned to have it automatically open up mail, so we will not be changing it.
