### ISSUE TITLE
Bread wording goes over picture- minor 

### ISSUE THREAD

**Issue by Ghermo35** [info442-su23/h-team#52]
The bread wording goes over the bread image in the game page. 
![CBA85D21-94F4-41AB-84FD-9C35667985D2](https://github.com/info442-su23/h-team/assets/43656152/891e6309-02aa-42ab-91a4-44e97c1d2f69)
If it could be lower it could be more appealing

**Comment by vuongb2** [comment]
Duplicate: https://github.com/info442-su23/h-team/issues/37
