### ISSUE TITLE
Feature Request -- Give explanations for right/wrong answers & maybe allow some options to have more than one correct answer? 

### ISSUE THREAD

**Issue by EloraHob** [info442-su23/h-team#53]
Certain materials such as cardboard and paper can be safely composted, but they are marked as recycle-only in the minigame. I think some clarification on items (plastic-coated cardboard vs. regular cardboard) or descriptions explaining why the item belongs to the indicated category (recycle, trash, compost) could be useful!

**Comment by vuongb2** [comment]
Duplicate: https://github.com/info442-su23/h-team/issues/48
